In [102]:
import pandas as pd
import numpy as np
#read in the data using pandas
df = pd.read_csv(r"C:\Users\ishme\Desktop\SteelPlateFaults.csv")
df1=df.copy()
#create a dataframe with all training data except the target column
X = df1.drop(columns="Class")
list_of_attributes=list(df.columns)
list_of_attributes.remove('Class')
print(len(list_of_attributes_1))

#separate target values
y = df["Class"].values

from sklearn.model_selection import train_test_split
#split dataset into train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, shuffle=True)



27


In [137]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
k=[1,3,5]
accuracy={}
for i in k:
    
    classifier = KNeighborsClassifier(n_neighbors = i)
    print(classifier)
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    result = confusion_matrix(y_test, y_pred)
    print("When k is ",i," Confusion Matrix:")
    print(result)
    result2 = accuracy_score(y_test,y_pred)
    accuracy[i]=result2
    
    print("When k is ",i," Accuracy:",result2)
value=list(accuracy.values())
key=list(accuracy.keys())
print("value of k for which accuracy is maximum is 3")
#print(np.shape(X_train))
y_train_r=np.reshape(y_train,(783,1))
y_test_r=np.reshape(y_test,(336,1))
#print(np.shape(r))

training_data = np.concatenate((X_train,y_train_r),axis=1)
train= pd.DataFrame(training_data, columns= df.columns)

train.to_csv('SteelPlateFaults-train.csv',index = False)

test_data = np.concatenate((X_test,y_test_r),axis=1)

test= pd.DataFrame(test_data, columns= df.columns)
test.to_csv('SteelPlateFaults-test.csv',index = False)



KNeighborsClassifier(n_neighbors=1)
When k is  1  Confusion Matrix:
[[ 81  27]
 [ 27 201]]
When k is  1  Accuracy: 0.8392857142857143
KNeighborsClassifier(n_neighbors=3)
When k is  3  Confusion Matrix:
[[ 83  25]
 [ 12 216]]
When k is  3  Accuracy: 0.8898809523809523
KNeighborsClassifier()
When k is  5  Confusion Matrix:
[[ 82  26]
 [  9 219]]
When k is  5  Accuracy: 0.8958333333333334
value of k for which accuracy is maximum is 3


In [112]:
#df_new=df.copy()
train1=train.copy()
for attribute in list_of_attributes:
  min=train1[attribute].min()
  max=train1[attribute].max()
  
  data=list(train1[attribute])
  for j in data:
    value=(j-min)/(max-min)
    
    train1[attribute]=train1[attribute].replace(j,value)
train1.to_csv('SteelPlateFaults-train-Normalised.csv',index = False)

  

In [113]:
test1=test.copy()
for attribute in list_of_attributes:
  min=test1[attribute].min()
  max=test1[attribute].max()
  
  data1=list(test1[attribute])
  for j in data1:
    value=(j-min)/(max-min)
    
    test1[attribute]=test1[attribute].replace(j,value)
test1.to_csv('SteelPlateFaults-test-normalised.csv',index = False)

In [106]:
accuracy1={}
train2 = train1.drop(columns="Class")
test2=test1.drop(columns="Class")
for i in k:
    
    classifier1 = KNeighborsClassifier(n_neighbors = i)
    classifier1.fit(train2,train1['Class'])
    y_pred1 = classifier1.predict(test2)
    result1 = confusion_matrix(test1['Class'], y_pred1)
    print("When k is ",i," Confusion Matrix:")
    print(result1)
    result2_n = accuracy_score(test1['Class'],y_pred1)
    accuracy1[i]=result2_n
    
    print("When k is ",i," Accuracy:",result2_n)
value1=list(accuracy1.values())
key1=list(accuracy1.keys())
#print("value of k for which accuracy is maximum is",key1[value1.index(max(value1))])
print("value of k for which accuracy is maximum is 5")


When k is  1  Confusion Matrix:
[[ 99   9]
 [  8 220]]
When k is  1  Accuracy: 0.9494047619047619
When k is  3  Confusion Matrix:
[[100   8]
 [  7 221]]
When k is  3  Accuracy: 0.9553571428571429
When k is  5  Confusion Matrix:
[[101   7]
 [  4 224]]
When k is  5  Accuracy: 0.9672619047619048
value of k for which accuracy is maximum is 5


In [107]:
#from sklearn.naive_bayes import GaussianNB
#Gaussian_clasifier = GaussianNB()
#Gaussian_clasifier.fit(X_train, y_train)


In [126]:
df_train=pd.read_csv('SteelPlateFaults-train.csv')
df_test=pd.read_csv('SteelPlateFaults-test.csv')

group_train= df_train.groupby('Class')
Class0_train= group_train.get_group(0).to_numpy()
Class0_train_n=Class0_train[:,:-1]


Class1_train= group_train.get_group(1).to_numpy()
Class1_train_n=Class1_train[:,:-1]

group_test= df_test.groupby('Class')
Class0_test= group_test.get_group(0).to_numpy()
Class1_test= group_test.get_group(1).to_numpy()
posterior_prob0=len(Class0_train_n)/(len(Class0_train_n)+len(Class1_train_n))
print(len(Class0_train_n)+len(Class1_train_n))
posterior_prob1=len(Class1_train_n)/(len(Class0_train_n)+len(Class1_train_n))


783


In [115]:
mean0= np.mean(Class0_train_n, axis=0)
mean_0=np.array(mean0)

mean1= np.mean(Class1_train_n, axis=0)
mean_1=np.array(mean1)
#print(mean0)

In [135]:
cov_0= np.cov((Class0_train_n).T)

cov_1= np.cov((Class1_train_n).T)
def likelihood(x,mean,covariance):
    matrix_multiply=np.dot(((x - mean).T), np.linalg.inv(covariance))
    exp_power=-0.5*(np.dot(matrix_multiply,(x-mean)))
    exponential=np.exp(exp_power)
    result=exponential/(((2*(np.pi))**13.5)*((np.linalg.det(covariance)) ** 0.5))
    return result


In [138]:
bayes_prediction=[]
xtest1=df_test[df_test.columns[:-1]]
for i in xtest1.itertuples(index=False) :
    c0 = likelihood(i, mean_0, cov_0) * posterior_prob0
    c1 = likelihood(i, mean_1, cov_1) * posterior_prob1
    if (c0 < c1):
        bayes_prediction.append(1)

    else:
        bayes_prediction.append(0)
print((bayes_prediction))
print(y_test)
confusion_mat=confusion_matrix(y_test,bayes_prediction)
print(confusion_mat)
accuracy=accuracy_score(df_test['Class'],bayes_prediction)
print('Accuracy is',accuracy)

[1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 

C:\Users\ishme\AppData\Local\Temp/ipykernel_21968/843629316.py:7: RuntimeWarning: overflow encountered in exp
  exponential=np.exp(exp_power)


In [144]:

accuracy_comparision={'KNN classifier':0.8958333333333334,'KNN classifier normalized':0.9672619047619048,'Bayes Classifier':0.6994047619047619}
new = pd.DataFrame.from_dict(accuracy_comparision.items())
print(new)

                           0         1
0             KNN classifier  0.895833
1  KNN classifier normalized  0.967262
2           Bayes Classifier  0.699405
